- name: Copy the Nginx main configuration file to the host
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Copy the Nginx configuration file to the host
  template:
    src: templates/default.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx service