#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx_configuration
- name: Install nginx
  import_tasks: install.yaml
- name: Certificates certbot
  import_tasks: certs.yaml
- name: Configuration
  import_tasks: configuration.yaml