# nginx_simple.yaml
user: "www-data"
worker_processes: "auto"
worker_connections: 1024
client_max_body_size: "10m"
access_log: "/var/log/nginx/access.log"
error_log: "/var/log/nginx/error.log"
caching: true
cache_size: "50m"
certbot_email: "senchuknazar6@gmail.com"

domains:
  website.com:
    ssl_enabled: false
    locations:
      - name: "main"
        path: "/"
        root: "/var/www/website"
        index: "index.html"
      
      - name: "images"
        path: "/images"
        root: "/var/www/website/assets"

  api.website.com:
    ssl_enabled: false  # Set to true if you want SSL
    locations:
      - name: "api"
        path: "/"
        hosts:
          - "192.168.1.10:8000"
          - "192.168.1.11:8000"
        lb_type: "least_conn"
        cache: true
        cache_duration: "10m"