[project]
name = "hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "fastapi>=0.121.0",
    "flask>=3.1.2",
    "sqlalchemy>=2.0.44",
]
